### ISSUE TITLE
biomart_domain: bio_data_uuid may contains non-unique bio_data_id values

### ISSUE THREAD

**Issue by mirasrael** [transmart/transmart-extensions#9]
Hi,
I created new database from transmart-data master branch and it looks like biomart.bio_data_uuid doesn't contains records for bio_assay_platform (which used for "Add new analysis" and "Add new assay" on "Browse" tab). I tried to insert them manually using following command:

```SQL
insert into biomart.bio_data_uid
(bio_data_id, unique_id, bio_data_type)
select p.bio_assay_platform_id, 'BAP:' || platform_accession, 'BIO_ASSAY_PLATFORM'
from biomart.bio_assay_platform p
left join biomart.bio_data_uid uid
on uid.bio_data_id = p.bio_assay_platform_id and uid.bio_data_type = 'BIO_ASSAY_PLATFORM'
where uid.bio_data_id is null;
```

but it fails with error: 

ERROR:  duplicate key value violates unique constraint "bio_data_uid_pk"
DETAIL:  Key (bio_data_id)=(169331) already exists.

I checked this id and it is already occupied by BIO_CONCEPT_CODE:
169331;"ASSAY_TYPE_OF_BM_STUDIED:PROTEIN";"BIO_CONCEPT_CODE"

The easiest way to avoid this problem from my point of view it make unique contraint by pair (bio_data_type, bio_data_id) and looking for unique code using filter by type additional to filter by id.

```java
BioData data = BioData.get(id);
```

should be replaced with something like:

```java
BioData data = BioData.findWhere(id: id, type: "BIO_ASSAY_PLATFORM");
```
It can be incapsulated into BioData to just provide method like:

```java
BioData.getUniqueId(platform)
```

Please, let me know what do you think about it and may be I'm doing something wrong. I can provide pull request if you like for this solution.

**Comment by Terry-Weymouth** [comment]
I just noticed that this issue was still open. Resolved?

**Comment by mirasrael** [comment]
@Terry-Weymouth Yes, it is. I checked latest `transmart_data` and bootstrap data for `BIO_ASSAY_PLATFORM` was changed to avoid conflicts with existing records. Also I found that all referred objects from `BIO_DATA_UID` uses same sequence, so it should prevent further conflicts.

**Comment by Terry-Weymouth** [comment]
Thanks.
